ROOT = './'
RAW = "/raw/"
JRAW='raw/'
PROCESSED = "/processed/"
JPROCESSED = "processed/"
FROM_RAW = 'from_raw'
PATH = 'H:/runs/run_' #change this to change save location
FAILED = 'FAILED'
RUNFILE = 'counter.txt'
RUNFOLDER = 'H:/runs/'
